-- D2: publicar deja de ser solo un estado. Cada publicacion guarda una instantanea inmutable del diagrama, con su
-- huella, y el modelo vivo sigue siendo el borrador de trabajo. Un caso de ejecucion se atara a una version, no a
-- filas que pueden cambiar debajo.
create table versiones_proceso (
    id                bigint       generated by default as identity primary key,
    empresa_id        bigint       not null,
    proceso_id        bigint       not null,
    numero            integer      not null,
    estado            varchar(20)  not null,
    fecha_publicacion timestamp(6) not null,
    publicado_por     bigint,
    huella            varchar(64)  not null,
    constraint uk_versiones_proceso_numero unique (proceso_id, numero),
    constraint ck_versiones_proceso_estado check (estado in ('VIGENTE', 'RETIRADA')),
    constraint ck_versiones_proceso_numero check (numero > 0),
    constraint fk_versiones_proceso_empresa foreign key (empresa_id) references empresas (id),
    constraint fk_versiones_proceso_proceso foreign key (proceso_id) references procesos (id),
    constraint fk_versiones_proceso_usuario foreign key (publicado_por) references usuarios (id)
);
create index idx_versiones_proceso_empresa on versiones_proceso (empresa_id);
create index idx_versiones_proceso_proceso on versiones_proceso (proceso_id);

-- La version vigente y su huella, en el proceso: decir si el borrador tiene cambios sin publicar no puede costar
-- una consulta a las versiones.
alter table procesos add column version_publicada integer;
alter table procesos add column huella_publicada varchar(64);
