-- D15: el historial deja de ser solo de los procesos. Un alta de usuario, un rol nuevo o el registro de la tienda
-- tambien son cambios de los que hay que responder, y no cuelgan de ningun proceso: proceso_id pasa a ser opcional y
-- cada fila dice de que recurso habla.
alter table historial_cambios alter column proceso_id drop not null;
alter table historial_cambios add column recurso_tipo varchar(30);
alter table historial_cambios add column recurso_id bigint;
alter table historial_cambios add constraint ck_historial_cambios_recurso
    check (recurso_tipo in ('PROCESO', 'ROL', 'USUARIO', 'EMPRESA'));
-- Lo que ya estaba escrito habla de procesos: que lo diga, para que ninguna fila se quede sin recurso.
update historial_cambios set recurso_tipo = 'PROCESO', recurso_id = proceso_id;

-- El historial de la tienda se lee entero y en orden, no por proceso.
create index idx_historial_cambios_empresa_fecha on historial_cambios (empresa_id, fecha_cambio);

-- D16: quien puede crear y editar pools y lanes deja de ser igual para todas las tiendas. Una fila por tienda, que
-- en el PR de la simulacion guardara ademas sus parametros.
create table configuracion_tienda (
    id                  bigint       generated by default as identity primary key,
    empresa_id          bigint       not null,
    politica_estructura varchar(30)  not null,
    version             bigint       default 0 not null,
    creado_por          bigint,
    fecha_creacion      timestamp(6) not null,
    modificado_por      bigint,
    fecha_modificacion  timestamp(6) not null,
    constraint uk_configuracion_tienda_empresa unique (empresa_id),
    constraint ck_configuracion_tienda_politica
        check (politica_estructura in ('SOLO_ADMINISTRADOR', 'ADMINISTRADOR_Y_EDITOR')),
    constraint fk_configuracion_tienda_empresa foreign key (empresa_id) references empresas (id)
);

-- Las tiendas que ya existen estrenan la politica que tenian hasta ahora: administrador y editor modelan.
insert into configuracion_tienda (empresa_id, politica_estructura, version, fecha_creacion, fecha_modificacion)
select id, 'ADMINISTRADOR_Y_EDITOR', 0, localtimestamp, localtimestamp from empresas;

-- D17: un usuario puede entrar con una contrasena temporal, y hasta que la cambie no puede hacer nada mas.
alter table usuarios add column debe_cambiar_clave boolean default false not null;
