-- D4: el estado de una ejecucion son instancias de actividad, no una tabla de tokens. Un caso corre sobre una
-- version publicada, cada paso por un nodo deja una fila en actividades_caso, y todo lo que ocurre queda escrito en
-- eventos_caso. Los tokens vivos de un caso son sus filas PENDIENTE y EN_ESPERA.

-- Un caso es un pedido: una ejecucion de la version que estaba vigente el dia que se abrio. La version no cambia
-- nunca, asi que lo que el caso recorre tampoco cambia debajo de el.
--
-- No lleva fecha_inicio ni iniciado_por: la auditoria de EntidadEditable ya guarda cuando se creo la fila y quien
-- la creo, y quien la creo es justo quien abrio el caso, o nadie cuando lo abrio un mensaje.
create table casos (
    id                 bigint       generated by default as identity primary key,
    empresa_id         bigint       not null,
    proceso_id         bigint       not null,
    version_proceso_id bigint       not null,
    referencia         varchar(120),
    estado             varchar(20)  not null,
    tick_inicio        integer      default 0 not null,
    tick_fin           integer,
    fecha_fin          timestamp(6),
    version            bigint       default 0 not null,
    creado_por         bigint,
    fecha_creacion     timestamp(6) not null,
    modificado_por     bigint,
    fecha_modificacion timestamp(6) not null,
    constraint ck_casos_estado check (estado in ('ABIERTO', 'TERMINADO', 'CANCELADO', 'FALLIDO', 'ERROR')),
    constraint fk_casos_empresa foreign key (empresa_id) references empresas (id),
    constraint fk_casos_proceso foreign key (proceso_id) references procesos (id),
    constraint fk_casos_version foreign key (version_proceso_id) references versiones_proceso (id)
);
-- Los dos accesos de la operacion: la lista de casos de un proceso por estado, y buscar el caso de un pedido por su
-- referencia, que es lo que hace la correlacion de cada mensaje que llega.
create index idx_casos_proceso_estado on casos (empresa_id, proceso_id, estado);
create index idx_casos_proceso_referencia on casos (empresa_id, proceso_id, referencia);

-- Cada paso por un nodo de la version. El nodo se guarda por id y por nombre, sin clave foranea: el id es el del
-- nodo dentro de la instantanea, y esa instantanea manda aunque el modelo vivo haya borrado el nodo despues.
create table actividades_caso (
    id                 bigint       generated by default as identity primary key,
    empresa_id         bigint       not null,
    caso_id            bigint       not null,
    nodo_id            bigint       not null,
    nodo_nombre        varchar(120) not null,
    tipo_nodo          varchar(20)  not null,
    subtipo            varchar(20)  not null,
    rol_proceso_id     bigint,
    estado             varchar(20)  not null,
    llegadas           integer      default 0 not null,
    asignado_a         bigint,
    tick_inicio        integer      default 0 not null,
    tick_fin           integer,
    version            bigint       default 0 not null,
    creado_por         bigint,
    fecha_creacion     timestamp(6) not null,
    modificado_por     bigint,
    fecha_modificacion timestamp(6) not null,
    constraint ck_actividades_caso_tipo check (tipo_nodo in ('ACTIVIDAD', 'GATEWAY', 'EVENTO')),
    constraint ck_actividades_caso_estado
        check (estado in ('PENDIENTE', 'EN_ESPERA', 'COMPLETADA', 'FALLIDA', 'OMITIDA')),
    constraint ck_actividades_caso_llegadas check (llegadas >= 0),
    constraint fk_actividades_caso_empresa foreign key (empresa_id) references empresas (id),
    constraint fk_actividades_caso_caso foreign key (caso_id) references casos (id),
    constraint fk_actividades_caso_usuario foreign key (asignado_a) references usuarios (id)
);
-- El motor busca los pendientes de un caso; la bandeja busca las tareas en espera de un rol.
create index idx_actividades_caso_caso_estado on actividades_caso (empresa_id, caso_id, estado);
create index idx_actividades_caso_rol_estado on actividades_caso (empresa_id, rol_proceso_id, estado);

-- La bitacora del caso: cada decision, cada tarea, cada error, en el orden en que pasaron. Solo se inserta.
create table eventos_caso (
    id         bigint        generated by default as identity primary key,
    empresa_id bigint        not null,
    caso_id    bigint        not null,
    tick       integer       default 0 not null,
    fecha      timestamp(6)  not null,
    tipo       varchar(30)   not null,
    detalle    varchar(2000) not null,
    autor_id   bigint,
    constraint ck_eventos_caso_tipo check (tipo in ('CASO_ABIERTO', 'NODO_ACTIVADO', 'TAREA_CREADA',
        'TAREA_COMPLETADA', 'GATEWAY_DECIDIO', 'MENSAJE_ENVIADO', 'MENSAJE_RECIBIDO', 'ENVIO_FALLIDO',
        'SIN_CAMINO', 'VARIABLE_AUSENTE', 'CASO_TERMINADO', 'CASO_CANCELADO')),
    constraint fk_eventos_caso_empresa foreign key (empresa_id) references empresas (id),
    constraint fk_eventos_caso_caso foreign key (caso_id) references casos (id),
    constraint fk_eventos_caso_usuario foreign key (autor_id) references usuarios (id)
);
-- La linea de tiempo de un caso se lee entera y en orden.
create index idx_eventos_caso_caso on eventos_caso (empresa_id, caso_id, id);
