-- D13: hasta ahora una tarea aparecia en la bandeja de su rol de proceso y punto, y quien entraba veia la bandeja
-- entera de la tienda. Esta tabla dice que roles tiene cada persona, para que pueda pedir solo lo suyo.
--
-- No sustituye al rol de acceso ni da permisos: quien completa una tarea sigue siendo cualquier administrador o
-- editor de la tienda. Es un filtro, no una puerta.
create table membresias_rol (
    id             bigint generated by default as identity primary key,
    empresa_id     bigint not null,
    usuario_id     bigint not null,
    rol_proceso_id bigint not null,
    constraint uk_membresias_rol_usuario_rol unique (usuario_id, rol_proceso_id),
    constraint fk_membresias_rol_empresa foreign key (empresa_id) references empresas (id),
    constraint fk_membresias_rol_usuario foreign key (usuario_id) references usuarios (id),
    constraint fk_membresias_rol_rol foreign key (rol_proceso_id) references roles_proceso (id)
);
-- La bandeja propia pregunta por los roles de una persona; el listado de un rol, por sus personas.
create index idx_membresias_rol_usuario on membresias_rol (empresa_id, usuario_id);
create index idx_membresias_rol_rol on membresias_rol (empresa_id, rol_proceso_id);
