-- D9: entre participantes no hay colas ni llamadas, hay bandejas. Lo que el proceso manda queda escrito en
-- mensajes_salientes hasta que el reloj lo entrega, y lo que llega queda escrito en mensajes_entrantes con lo que
-- se hizo con el. Las dos tablas se leen como lo que son: el correo que salio y el correo que entro.
--
-- Ninguna de las dos lleva version ni auditoria de usuario. Un mensaje no es un documento que alguien edita: lo
-- escribe el motor dentro del bloqueo del caso y lo unico que cambia despues es si se entrego. Quien lo provoco ya
-- esta en la bitacora del caso, que es donde se va a buscar.

-- Lo que el proceso mando y todavia no ha llegado a su destino. El mensaje se guarda por id y por nombre, sin clave
-- foranea, igual que los nodos de actividades_caso: el id es el de la instantanea de la version, y el modelo vivo
-- puede haber borrado ese mensaje despues sin que lo que el caso envio deje de ser cierto. Por eso tambien viaja el
-- nombre del participante destino y no su id.
create table mensajes_salientes (
    id                  bigint       generated by default as identity primary key,
    empresa_id          bigint       not null,
    caso_id             bigint       not null,
    mensaje_id          bigint       not null,
    nombre              varchar(120) not null,
    pool_destino_nombre varchar(120) not null,
    integracion         varchar(20)  not null,
    tipo_destino        varchar(20),
    clave               varchar(120),
    estado              varchar(20)  not null,
    tick_creacion       integer      default 0 not null,
    tick_entrega        integer      default 0 not null,
    intentos            integer      default 0 not null,
    error               varchar(500),
    fecha               timestamp(6) not null,
    constraint ck_mensajes_salientes_estado check (estado in ('PENDIENTE', 'ENTREGADO', 'FALLIDO')),
    constraint ck_mensajes_salientes_integracion
        check (integracion in ('NINGUNA', 'CLIENTE', 'PAGOS', 'TRANSPORTE', 'NOTIFICACIONES')),
    constraint ck_mensajes_salientes_tipo_destino
        check (tipo_destino is null or tipo_destino in ('CORREO', 'SERVICIO_WEB', 'COLA')),
    constraint ck_mensajes_salientes_intentos check (intentos >= 0),
    constraint fk_mensajes_salientes_empresa foreign key (empresa_id) references empresas (id),
    constraint fk_mensajes_salientes_caso foreign key (caso_id) references casos (id)
);
-- Mover el reloj pregunta que hay pendiente y ya vencido; el detalle de un caso, que mando y que recibio.
create index idx_mensajes_salientes_vencidos on mensajes_salientes (empresa_id, estado, tick_entrega);
create index idx_mensajes_salientes_caso on mensajes_salientes (empresa_id, caso_id, id);

-- Lo que llego al proceso, venga de un socio simulado o de alguien que lo mando a mano, y a que caso fue a parar.
-- Cuelga del proceso y no del caso porque un entrante puede no tener caso: el que abre uno todavia no lo tiene, y
-- el que no corresponde a ninguno se queda escrito igual, que es lo que se mira cuando algo no llego a su sitio.
create table mensajes_entrantes (
    id            bigint       generated by default as identity primary key,
    empresa_id    bigint       not null,
    proceso_id    bigint       not null,
    caso_id       bigint,
    nombre        varchar(120) not null,
    clave         varchar(120),
    origen        varchar(30)  not null,
    clave_externa varchar(120),
    resultado     varchar(20)  not null,
    tick          integer      default 0 not null,
    fecha         timestamp(6) not null,
    constraint ck_mensajes_entrantes_origen check (origen in ('MANUAL', 'CLIENTE_SIMULADO', 'SIMULADOR_PAGOS',
        'SIMULADOR_TRANSPORTE', 'SIMULADOR_NOTIFICACIONES')),
    constraint ck_mensajes_entrantes_resultado
        check (resultado in ('ENTREGADO_A_CASO', 'CASO_NUEVO', 'EN_ESPERA', 'DESCARTADO')),
    -- La clave externa la pone quien manda el mensaje, asi que solo es unica dentro de su tienda: dos tiendas
    -- pueden llamar igual a dos pedidos distintos sin saber la una de la otra.
    constraint uk_mensajes_entrantes_clave_externa unique (empresa_id, clave_externa),
    constraint fk_mensajes_entrantes_empresa foreign key (empresa_id) references empresas (id),
    constraint fk_mensajes_entrantes_proceso foreign key (proceso_id) references procesos (id),
    constraint fk_mensajes_entrantes_caso foreign key (caso_id) references casos (id)
);
-- La bandeja de entrada de un proceso, y los que se quedaron esperando a que su caso llegue a esperarlos.
create index idx_mensajes_entrantes_proceso on mensajes_entrantes (empresa_id, proceso_id, id);
create index idx_mensajes_entrantes_espera on mensajes_entrantes (empresa_id, proceso_id, resultado, nombre);
