-- Esquema inicial, escrito a partir del DDL que Hibernate genera para las entidades.
-- SQL comun a H2 y PostgreSQL; lo que solo sabe expresar un motor va en db/migration/{h2,postgresql}.
-- Convenciones: uk_ unico, ck_ check, fk_ llave foranea, idx_ indice. Toda tabla de una empresa indexa empresa_id.

create table empresas (
    id              bigint generated by default as identity primary key,
    nombre          varchar(120) not null,
    nit             varchar(20)  not null,
    correo_contacto varchar(254) not null,
    fecha_registro  date         not null,
    constraint uk_empresas_nit unique (nit)
);

-- El correo es el usuario del login, que todavia no conoce la empresa: unico en toda la plataforma.
create table usuarios (
    id            bigint generated by default as identity primary key,
    empresa_id    bigint       not null,
    nombre        varchar(120) not null,
    email         varchar(254) not null,
    password_hash varchar(100) not null,
    rol_acceso    varchar(20)  not null,
    activo        boolean      not null,
    constraint uk_usuarios_email unique (email),
    constraint ck_usuarios_rol_acceso check (rol_acceso in ('ADMINISTRADOR', 'EDITOR', 'SOLO_LECTURA')),
    constraint fk_usuarios_empresa foreign key (empresa_id) references empresas (id)
);
create index idx_usuarios_empresa on usuarios (empresa_id);

create table procesos (
    id                 bigint generated by default as identity primary key,
    empresa_id         bigint        not null,
    nombre             varchar(120)  not null,
    descripcion        varchar(4000) not null,
    categoria          varchar(80)   not null,
    estado             varchar(20)   not null,
    activo             boolean       not null,
    fecha_creacion     timestamp(6)  not null,
    fecha_modificacion timestamp(6)  not null,
    constraint ck_procesos_estado check (estado in ('BORRADOR', 'PUBLICADO')),
    constraint fk_procesos_empresa foreign key (empresa_id) references empresas (id)
);
create index idx_procesos_empresa on procesos (empresa_id);

create table roles_proceso (
    id          bigint generated by default as identity primary key,
    empresa_id  bigint       not null,
    nombre      varchar(80)  not null,
    descripcion varchar(500),
    activo      boolean      not null,
    constraint fk_roles_proceso_empresa foreign key (empresa_id) references empresas (id)
);
create index idx_roles_proceso_empresa on roles_proceso (empresa_id);

create table historial_cambios (
    id                 bigint generated by default as identity primary key,
    empresa_id         bigint       not null,
    proceso_id         bigint       not null,
    autor_id           bigint       not null,
    fecha_cambio       timestamp(6) not null,
    descripcion_cambio varchar(500) not null,
    constraint fk_historial_cambios_empresa foreign key (empresa_id) references empresas (id),
    constraint fk_historial_cambios_proceso foreign key (proceso_id) references procesos (id),
    constraint fk_historial_cambios_autor foreign key (autor_id) references usuarios (id)
);
create index idx_historial_cambios_empresa on historial_cambios (empresa_id);
create index idx_historial_cambios_proceso on historial_cambios (proceso_id);

create table pools (
    id                bigint generated by default as identity primary key,
    empresa_id        bigint       not null,
    proceso_id        bigint       not null,
    nombre            varchar(120) not null,
    tipo_participante varchar(20)  not null,
    caja_negra        boolean      not null,
    orden             integer      not null,
    constraint ck_pools_tipo_participante
        check (tipo_participante in ('EMPRESA', 'CLIENTE', 'PROVEEDOR', 'SISTEMA_EXTERNO')),
    constraint fk_pools_empresa foreign key (empresa_id) references empresas (id),
    constraint fk_pools_proceso foreign key (proceso_id) references procesos (id)
);
create index idx_pools_empresa on pools (empresa_id);
create index idx_pools_proceso on pools (proceso_id);

create table lanes (
    id             bigint generated by default as identity primary key,
    empresa_id     bigint       not null,
    pool_id        bigint       not null,
    rol_proceso_id bigint       not null,
    nombre         varchar(120) not null,
    orden          integer      not null,
    constraint fk_lanes_empresa foreign key (empresa_id) references empresas (id),
    constraint fk_lanes_pool foreign key (pool_id) references pools (id),
    constraint fk_lanes_rol_proceso foreign key (rol_proceso_id) references roles_proceso (id)
);
create index idx_lanes_empresa on lanes (empresa_id);
create index idx_lanes_pool on lanes (pool_id);
create index idx_lanes_rol_proceso on lanes (rol_proceso_id);

-- Actividades y gateways comparten tabla (herencia SINGLE_TABLE) y se distinguen por tipo_nodo.
create table nodos_flujo (
    id           bigint generated by default as identity primary key,
    empresa_id   bigint        not null,
    lane_id      bigint        not null,
    tipo_nodo    varchar(31)   not null,
    nombre       varchar(120)  not null,
    posicion_x   integer       not null,
    posicion_y   integer       not null,
    descripcion  varchar(1000),
    tipo_gateway varchar(20),
    constraint ck_nodos_flujo_tipo_nodo check (tipo_nodo in ('ACTIVIDAD', 'GATEWAY')),
    constraint ck_nodos_flujo_tipo_gateway check (tipo_gateway in ('EXCLUSIVO', 'PARALELO', 'INCLUSIVO')),
    constraint ck_nodos_flujo_gateway_con_tipo check (tipo_nodo <> 'GATEWAY' or tipo_gateway is not null),
    constraint fk_nodos_flujo_empresa foreign key (empresa_id) references empresas (id),
    constraint fk_nodos_flujo_lane foreign key (lane_id) references lanes (id)
);
create index idx_nodos_flujo_empresa on nodos_flujo (empresa_id);
create index idx_nodos_flujo_lane on nodos_flujo (lane_id);

-- pool_id repite el pool de ambos nodos: el arco nunca cruza pools. El indice unico ya sirve para buscar por origen.
create table arcos (
    id         bigint generated by default as identity primary key,
    empresa_id bigint       not null,
    pool_id    bigint       not null,
    origen_id  bigint       not null,
    destino_id bigint       not null,
    etiqueta   varchar(120),
    condicion  varchar(500),
    constraint uk_arcos_origen_destino unique (origen_id, destino_id),
    constraint ck_arcos_sin_bucle check (origen_id <> destino_id),
    constraint fk_arcos_empresa foreign key (empresa_id) references empresas (id),
    constraint fk_arcos_pool foreign key (pool_id) references pools (id),
    constraint fk_arcos_origen foreign key (origen_id) references nodos_flujo (id),
    constraint fk_arcos_destino foreign key (destino_id) references nodos_flujo (id)
);
create index idx_arcos_empresa on arcos (empresa_id);
create index idx_arcos_pool on arcos (pool_id);
create index idx_arcos_destino on arcos (destino_id);

create table mensajes (
    id              bigint generated by default as identity primary key,
    empresa_id      bigint        not null,
    proceso_id      bigint        not null,
    pool_origen_id  bigint        not null,
    pool_destino_id bigint        not null,
    nombre          varchar(120)  not null,
    contenido       varchar(2000) not null,
    constraint ck_mensajes_pools_distintos check (pool_origen_id <> pool_destino_id),
    constraint fk_mensajes_empresa foreign key (empresa_id) references empresas (id),
    constraint fk_mensajes_proceso foreign key (proceso_id) references procesos (id),
    constraint fk_mensajes_pool_origen foreign key (pool_origen_id) references pools (id),
    constraint fk_mensajes_pool_destino foreign key (pool_destino_id) references pools (id)
);
create index idx_mensajes_empresa on mensajes (empresa_id);
create index idx_mensajes_proceso on mensajes (proceso_id);
create index idx_mensajes_pool_origen on mensajes (pool_origen_id);
create index idx_mensajes_pool_destino on mensajes (pool_destino_id);

create table correlaciones (
    id         bigint generated by default as identity primary key,
    empresa_id bigint       not null,
    mensaje_id bigint       not null,
    criterio   varchar(120) not null,
    constraint uk_correlaciones_mensaje unique (mensaje_id),
    constraint fk_correlaciones_empresa foreign key (empresa_id) references empresas (id),
    constraint fk_correlaciones_mensaje foreign key (mensaje_id) references mensajes (id)
);
create index idx_correlaciones_empresa on correlaciones (empresa_id);
