-- D34: las revisiones con IA viven en la base, para que todas las instancias de la API vean las mismas. Cada respuesta
-- del modelo deja una fila. La mas reciente de un proceso se devuelve otra vez mientras su diagrama no cambie, lo que
-- dice la huella (el SHA-256 del diagrama contado en texto), y las de la ventana cuentan para el limite de la tienda.
-- hallazgos es la lista de la respuesta, en JSON.
create table revisiones_ia (
    id         bigint generated by default as identity primary key,
    empresa_id bigint       not null,
    proceso_id bigint       not null,
    huella     varchar(64)  not null,
    resumen    text         not null,
    hallazgos  text         not null,
    fecha      timestamp(6) not null,
    constraint fk_revisiones_ia_empresa foreign key (empresa_id) references empresas (id),
    constraint fk_revisiones_ia_proceso foreign key (proceso_id) references procesos (id)
);
create index idx_revisiones_ia_empresa_fecha on revisiones_ia (empresa_id, fecha);
create index idx_revisiones_ia_proceso_fecha on revisiones_ia (proceso_id, fecha);
