-- HU-03 y D34: los intentos fallidos de login viven en la base, para que el limite cuente lo mismo en todas las
-- instancias de la API. clave es el correo en minusculas y la IP de quien lo intenta. No cuelga de una tienda: quien
-- falla el login todavia no tiene una. La purga nocturna se lleva lo que ya salio de la ventana.
create table intentos_login (
    id    bigint generated by default as identity primary key,
    clave varchar(320) not null,
    fecha timestamp(6) not null
);
create index idx_intentos_login_clave_fecha on intentos_login (clave, fecha);
