-- D34: la cola de trabajos, en la misma base. Un trabajo es algo que tarda o que puede fallar y conviene reintentar,
-- como una exportacion grande: se encola dentro de la transaccion que lo pide, y lo toma la instancia que este libre.
-- empresa_id es de quien es el trabajo, y sirve para que una tienda no ocupe a todos los trabajadores; los trabajos
-- del sistema no tienen tienda. disponible_desde es cuando se puede tomar: al encolarlo, y despues de cada fallo, con
-- una espera que se duplica en cada intento.
create table trabajos (
    id               bigint generated by default as identity primary key,
    empresa_id       bigint,
    tipo             varchar(60)   not null,
    datos            text          not null,
    estado           varchar(20)   not null,
    intentos         integer       not null,
    maximo_intentos  integer       not null,
    disponible_desde timestamp(6)  not null,
    tomado_por       varchar(100),
    tomado_en        timestamp(6),
    ultimo_error     varchar(2000),
    creado_en        timestamp(6)  not null,
    terminado_en     timestamp(6),
    constraint fk_trabajos_empresa foreign key (empresa_id) references empresas (id),
    constraint ck_trabajos_estado check (estado in ('PENDIENTE', 'EN_CURSO', 'HECHO', 'FALLIDO')),
    constraint ck_trabajos_intentos check (intentos >= 0 and maximo_intentos >= 1)
);
create index idx_trabajos_disponibles on trabajos (disponible_desde, id) where estado = 'PENDIENTE';
create index idx_trabajos_en_curso on trabajos (empresa_id) where estado = 'EN_CURSO';
create index idx_trabajos_terminados on trabajos (terminado_en) where estado in ('HECHO', 'FALLIDO');
