-- Los enlaces que manda el correo: verificar el correo, recuperar la clave y aceptar una invitacion. Cada uno sirve
-- una vez y vence; de su token solo se guarda el SHA-256, porque el token en claro viaja en el correo y en ningun otro
-- sitio. usuario_id es de quien es el enlace; una invitacion todavia no tiene usuario, y lleva el correo y el rol con
-- que se creara.
create table enlaces_de_un_uso (
    id          bigint generated by default as identity primary key,
    empresa_id  bigint       not null,
    usuario_id  bigint,
    email       varchar(254) not null,
    proposito   varchar(30)  not null,
    rol_acceso  varchar(20),
    token_hash  varchar(64)  not null,
    creado_en   timestamp(6) not null,
    vence_en    timestamp(6) not null,
    usado_en    timestamp(6),
    constraint fk_enlaces_empresa foreign key (empresa_id) references empresas (id),
    constraint fk_enlaces_usuario foreign key (usuario_id) references usuarios (id),
    constraint uk_enlaces_token unique (token_hash),
    constraint ck_enlaces_proposito check (proposito in ('VERIFICAR_CORREO', 'RECUPERAR_CLAVE', 'INVITACION')),
    constraint ck_enlaces_invitacion check (proposito <> 'INVITACION' or rol_acceso is not null)
);
create index idx_enlaces_vigentes on enlaces_de_un_uso (usuario_id, proposito) where usado_en is null;
create index idx_enlaces_vencimiento on enlaces_de_un_uso (vence_en);

-- Cuando el usuario probo que el correo es suyo. Quien ya estaba no tiene que verificar nada: se da por bueno.
alter table usuarios add column correo_verificado_en timestamp(6);
update usuarios set correo_verificado_en = current_timestamp;
