-- HU-23: una empresa comparte un proceso en solo lectura con otras. Es la unica excepcion al aislamiento (HU-03).
-- empresa_id es la duena del proceso; empresa_invitada_id, la que lo puede leer.
create table procesos_compartidos (
    id                  bigint generated by default as identity primary key,
    empresa_id          bigint       not null,
    proceso_id          bigint       not null,
    empresa_invitada_id bigint       not null,
    fecha_compartido    timestamp(6) not null,
    constraint uk_procesos_compartidos_proceso_invitada unique (proceso_id, empresa_invitada_id),
    constraint ck_procesos_compartidos_con_otra_empresa check (empresa_invitada_id <> empresa_id),
    constraint fk_procesos_compartidos_empresa foreign key (empresa_id) references empresas (id),
    constraint fk_procesos_compartidos_proceso foreign key (proceso_id) references procesos (id),
    constraint fk_procesos_compartidos_invitada foreign key (empresa_invitada_id) references empresas (id)
);
create index idx_procesos_compartidos_empresa on procesos_compartidos (empresa_id);
create index idx_procesos_compartidos_invitada on procesos_compartidos (empresa_invitada_id);
