-- Sesiones con refresh token. Cada login abre una sesion y su refresh token rota en cada renovacion. Cerrarla (logout,
-- un refresh token reutilizado, desactivar al usuario o cambiarle el rol) invalida todos sus tokens a la vez.
-- codigo es el identificador opaco que viaja en el claim sid del access token.
create table sesiones (
    id           bigint generated by default as identity primary key,
    empresa_id   bigint       not null,
    usuario_id   bigint       not null,
    codigo       varchar(36)  not null,
    fecha_inicio timestamp(6) not null,
    fecha_cierre timestamp(6),
    constraint uk_sesiones_codigo unique (codigo),
    constraint fk_sesiones_empresa foreign key (empresa_id) references empresas (id),
    constraint fk_sesiones_usuario foreign key (usuario_id) references usuarios (id)
);
create index idx_sesiones_empresa on sesiones (empresa_id);
create index idx_sesiones_usuario on sesiones (usuario_id);
create index idx_sesiones_cierre on sesiones (fecha_cierre);

-- Del refresh token solo se guarda su hash SHA-256: quien lea la base no puede usarlo. fecha_uso marca el que ya rot.
create table refresh_tokens (
    id               bigint generated by default as identity primary key,
    empresa_id       bigint       not null,
    sesion_id        bigint       not null,
    token_hash       varchar(64)  not null,
    fecha_emision    timestamp(6) not null,
    fecha_expiracion timestamp(6) not null,
    fecha_uso        timestamp(6),
    constraint uk_refresh_tokens_hash unique (token_hash),
    constraint fk_refresh_tokens_empresa foreign key (empresa_id) references empresas (id),
    constraint fk_refresh_tokens_sesion foreign key (sesion_id) references sesiones (id)
);
create index idx_refresh_tokens_empresa on refresh_tokens (empresa_id);
create index idx_refresh_tokens_sesion on refresh_tokens (sesion_id);
