-- Idempotency-Key: un POST reintentado con la misma clave recibe la respuesta guardada en vez de crear otro recurso.
-- La clave es de cada usuario. huella es el SHA-256 del metodo, la ruta y el cuerpo: la misma clave con otra peticion
-- se rechaza. estado queda vacio mientras la primera peticion sigue en curso.
create table claves_idempotencia (
    id             bigint generated by default as identity primary key,
    empresa_id     bigint         not null,
    usuario_id     bigint         not null,
    clave          varchar(100)   not null,
    huella         varchar(64)    not null,
    estado         integer,
    cuerpo         varchar(16000),
    ubicacion      varchar(500),
    fecha_creacion timestamp(6)   not null,
    constraint uk_claves_idempotencia_usuario_clave unique (usuario_id, clave),
    constraint fk_claves_idempotencia_empresa foreign key (empresa_id) references empresas (id),
    constraint fk_claves_idempotencia_usuario foreign key (usuario_id) references usuarios (id)
);
create index idx_claves_idempotencia_empresa on claves_idempotencia (empresa_id);
